name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"
          fail-build: false
          severity-cutoff: critical
#       - name: upload Anchore scan SARIF report
#         uses: github/codeql-action/upload-sarif@v2
#         with:
#           sarif_file: ${{ steps.scan.outputs.sarif }}
#       - name: Inspect action SARIF report
#         run: cat ${{ steps.scan.outputs.sarif }}
